local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader><space>', builtin.find_files)
vim.keymap.set('n', '<leader>fg', builtin.live_grep)
vim.keymap.set('n', '<leader>fb', builtin.current_buffer_fuzzy_find)
vim.keymap.set('n', '<leader>bb', builtin.buffers)
vim.keymap.set('n', '<leader>gs', builtin.grep_string)
vim.keymap.set('n', '<leader>fs', builtin.lsp_workspace_symbols)
vim.keymap.set('n', '<leader>fr', builtin.lsp_references)
vim.keymap.set('n', '<leader>fd', builtin.lsp_definitions)
vim.keymap.set('n', '<leader>fi', builtin.lsp_implementations)
